Asman Umbetov Tasks 31-40
fastndead/ui-internship-lwo2 pull request #5
Opened 2019-09-13 07:32 UTC by fastndead

2019-09-16 08:08 UTC, vovcyan requested changes

2019-09-16 08:08 UTC, vovcyan commented on tasks/33_array-plus-array/array-plus-array.js
> +    let numberFromArr1 = arr1[i] ? arr1[i] : 0;
const

2019-09-16 08:08 UTC, vovcyan commented on tasks/36_row-weight/row-weight.js
> +      flag? acc[0] += current : acc[1] += current;
What is it?
Rewrite it with If condition

2019-09-16 09:25 UTC, vovcyan approved these changes

2019-09-17 06:01 UTC, savchukm approved these changes

2019-09-17 06:01 UTC, savchukm commented on tasks/37_min-number-to-prime/min-number-to-prime.js
> +  if (isPrime) {
return `!!isPrime` is better solution here

2019-09-17 06:02 UTC, merged

2019-09-17 06:10 UTC, alexkond approved these changes

2019-09-17 06:10 UTC, alexkond commented on tasks/32_numbers-to-reversed-array/numbers-to-reversed-array.js
> +      .map((item) => parseInt(item));
You could just pass `parseInt` function to `.map()`