Asman Umbetov Tasks 51-60
fastndead/ui-internship-lwo2 pull request #7
Opened 2019-09-17 07:35 UTC by fastndead

2019-09-17 17:17 UTC, vovcyan requested changes

2019-09-17 17:17 UTC, vovcyan commented on tasks/51_abbreviated-name/abbreviated-name.js
> + * Abbreviates every word in string except for the first word
Please add example

2019-09-19 05:07 UTC, savchukm requested changes

2019-09-19 05:07 UTC, savchukm commented on tasks/52_sum-all-numbers-in-range/sum-all-numbers-in-range.js
> +  for (let i = Math.min(...arr); i <= Math.max(...arr); i++) {
Math.min and Math.max will be calculated on every iteration. I'd suggest to move it to a variable

2019-09-19 11:23 UTC, savchukm approved these changes

2019-09-19 12:00 UTC, vovcyan approved these changes

2019-09-19 12:01 UTC, merged